
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-multidrawarraysindirect.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-invalidatesubframebuffer.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-vertexbinddivisor.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-diapatchcompute.cpp ./temp
cp basic/gl43/gl43-copyimagesubdata.cpp ./temp
cp basic/gl43/gl43-copyimagesubdata.cpp ./temp
cp basic/gl43/gl43-copyimagesubdata.cpp ./temp
cp basic/gl43/gl43-copyimagesubdata.cpp ./temp
cp basic/gl43/gl43-copyimagesubdata.cpp ./temp
cp basic/gl43/gl43-copyimagesubdata.cpp ./temp
cp basic/gl43/gl43-copyimagesubdata.cpp ./temp
cp basic/gl43/gl43-diapatchcomputeindirect.cpp ./temp
cp basic/gl43/gl43-bindvertexbuffer.cpp ./temp
cp basic/gl43/gl43-bindvertexbuffer.cpp ./temp
cp basic/gl43/gl43-InvalidateBufferSubData.cpp ./temp
cp basic/gl43/gl43-InvalidateBufferSubData.cpp ./temp
cp basic/gl43/gl43-InvalidateBufferSubData.cpp ./temp
cp basic/gl43/gl43-clearbufferdata.cpp ./temp
cp basic/gl43/gl43-invalidatebufferdata.cpp ./temp
cp basic/gl43/gl43-invalidatebufferdata.cpp ./temp
cp basic/gl43/gl43-invalidatebufferdata.cpp ./temp
cp basic/gl43/gl43-invalidatebufferdata.cpp ./temp
cp basic/gl43/gl43-invalidatebufferdata.cpp ./temp
cp basic/gl43/gl43-multidrawelementsindirect.cpp ./temp
cp basic/gl43/gl43-texstorage2dms.cpp ./temp
cp basic/gl43/gl43-texstorage2dms.cpp ./temp
cp basic/gl43/gl43-texstorage2dms.cpp ./temp
cp basic/gl43/gl43-texstorage2dms.cpp ./temp
cp basic/gl43/gl43-texstorage2dms.cpp ./temp
cp basic/gl43/gl43-texstorage2dms.cpp ./temp
cp basic/gl43/gl43-texstorage2dms.cpp ./temp
cp basic/gl43/gl43-texstorage3dms.cpp ./temp
cp basic/gl43/gl43-texstorage3dms.cpp ./temp
cp basic/gl43/gl43-texbufferrange.cpp ./temp
cp basic/gl43/gl43-invalidateframebuffer1.cpp ./temp
cp basic/gl43/gl43-invalidateframebuffer1.cpp ./temp
cp basic/gl43/gl43-objectlabel.cpp ./temp
cp basic/gl43/gl43-objectlabel.cpp ./temp
cp basic/gl43/gl43-objectlabel.cpp ./temp
cp basic/gl43/gl43-objectlabel.cpp ./temp
cp basic/gl43/gl43-objectlabel.cpp ./temp
cp basic/gl43/gl43-objectlabel.cpp ./temp
cp basic/gl43/gl43-uniformbuffer_row.cpp ./temp
cp basic/gl43/gl43-uniformbuffer_row.cpp ./temp
cp basic/gl43/gl43-equalspace_cw.cpp ./temp
cp basic/gl43/gl43-equalspace_cw.cpp ./temp
cp basic/gl43/gl43-equalspace_cw.cpp ./temp
cp basic/gl43/gl43-equalspace_cw.cpp ./temp
cp basic/gl43/gl43-equalspace_cw.cpp ./temp
cp basic/gl43/gl43-equalspace_cw.cpp ./temp
cp basic/gl43/gl43-equalspace_cw.cpp ./temp
cp basic/gl43/gl43-cullface.cpp ./temp
cp basic/gl43/gl43-textureview.cpp ./temp
cp basic/gl43/gl43-textureview.cpp ./temp
cp basic/gl43/gl43-textureview.cpp ./temp
cp basic/gl43/gl43-subroutine.cpp ./temp
cp basic/gl43/gl43-subroutine.cpp ./temp
cp basic/gl43/gl43-subroutine.cpp ./temp
cp basic/gl43/gl43-invalidateteximage.cpp ./temp
cp basic/gl43/gl43-cubezier.cpp ./temp
cp basic/gl43/gl43-cubezier.cpp ./temp
cp basic/gl43/gl43-cubezier.cpp ./temp
cp basic/gl43/gl43-yasuo.cpp ./temp
cp basic/gl43/gl43-skybox.cpp ./temp
cp basic/gl43/simple.c ./temp
cp basic/gl43/simple.c ./temp
cp basic/gl43/simple.c ./temp
cp basic/gl43/simple.c ./temp
cp basic/gl43/simple.c ./temp
cp basic/gl43/simple.c ./temp
cp basic/gl42/gl42-drawarraysindirect.cpp ./temp
cp basic/gl42/gl42-drawarraysindirect.cpp ./temp
cp basic/gl42/gl42-drawarraysinstanced-.cpp ./temp
cp basic/gl42/gl42-drawelementsinstanced-.cpp ./temp
cp basic/gl42/gl42-drawelementsinstanced-.cpp ./temp
cp basic/gl42/gl42-drawelementsinstanced-.cpp ./temp
cp basic/gl42/gl42-drawelementsindirect.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline1.cpp ./temp
cp basic/gl42/gl42-pipeline.cpp ./temp
cp basic/gl42/gl42-texstorage3d.cpp ./temp
cp basic/gl42/gl42-texstorage3d.cpp ./temp
cp basic/gl42/gl42-texstorage3d.cpp ./temp
cp basic/gl42/gl42-texstorage3d.cpp ./temp
cp basic/gl42/gl42-texstorage3d.cpp ./temp
cp basic/gl42/gl42-shaderprogram1.cpp ./temp
cp basic/gl42/gl42-shaderprogram1.cpp ./temp
cp basic/gl42/gl42-texstorage2d1.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-drawfeedbackstreaminstanced.cpp ./temp
cp basic/gl42/gl42-getInternalformat.cpp ./temp
cp basic/gl42/gl42-drawtransformfeedbackinstanced.cpp ./temp
cp basic/gl42/gl42-drawtransformfeedbackinstanced.cpp ./temp
cp basic/gl42/gl42-drawtransformfeedbackinstanced.cpp ./temp
cp basic/gl42/gl42-atomiccounter.cpp ./temp
cp basic/gl42/gl42-atomiccounter.cpp ./temp
cp basic/gl42/gl42-atomiccounter.cpp ./temp
cp basic/gl42/gl42-atomiccounter.cpp ./temp
cp basic/gl42/gl42-texstorage1d.cpp ./temp
cp basic/gl42/gl42-texstorage1d.cpp ./temp
cp basic/gl41/gl41_depthf.cpp ./temp
cp basic/gl41/gl41_depthf.cpp ./temp
cp basic/gl41/gl41-queryindexed.cpp ./temp
cp basic/gl41/gl41-queryindexed.cpp ./temp
cp basic/gl41/gl41-queryindexed.cpp ./temp
cp basic/gl41/gl41-queryindexed.cpp ./temp
cp basic/gl41/gl41-queryindexed.cpp ./temp
cp basic/gl41/gl41-queryindexed.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-vertexattrib.cpp ./temp
cp basic/gl41/gl41-ScissorArrayv.cpp ./temp
cp basic/gl41/gl41-glDepthRangef.cpp ./temp
cp basic/gl41/gl41_programbinary.cpp ./temp
cp basic/gl41/gl41_programbinary.cpp ./temp
cp basic/gl41/gl41-ScissorIndexed.cpp ./temp
cp basic/gl41/gl41-ScissorIndexedv.cpp ./temp
cp basic/gl41/gl41-glViewportArrayv.cpp ./temp
cp basic/gl41/gl41_glPatchParameterfv.cpp ./temp
cp basic/gl41/gl41_glProgramParameteri.cpp ./temp
cp basic/gl41/gl41_glProgramParameteri.cpp ./temp
cp basic/gl41/gl41_glProgramParameteri.cpp ./temp
cp basic/gl41/gl41_glProgramParameteri.cpp ./temp
cp basic/gl41/gl41_glProgramParameteri.cpp ./temp
cp basic/gl41/gl41_glProgramParameteri.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxi_iv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxui_uiv.cpp ./temp
cp basic/gl41/gl41_getShaderPrecisionFormat.cpp ./temp
cp basic/gl41/gl41_getShaderPrecisionFormat.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41_glProgramUniformxMatrixfv.cpp ./temp
cp basic/gl41/gl41-glGet_v.cpp ./temp
cp basic/gl41/gl41-glGet_v.cpp ./temp
cp basic/gl40/gl40-blendseperatei.cpp ./temp
cp basic/gl40/gl40-blendseperatei.cpp ./temp
cp basic/gl40/gl40-blendseperatei.cpp ./temp
cp basic/gl40/gl40-blendseperatei.cpp ./temp
cp basic/gl40/gl40-blendseperatei.cpp ./temp
cp basic/gl40/gl40-blendseperatei.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-uniformmatrix.cpp ./temp
cp basic/gl40/gl40-blendi.cpp ./temp
cp basic/gl40/gl40-blendi.cpp ./temp
cp basic/gl40/gl40-geom_subroutine.cpp ./temp
cp basic/gl40/gl40-geom_subroutine.cpp ./temp
cp basic/gl40/gl40-geom_subroutine.cpp ./temp
cp basic/gl40/gl40-geom_subroutine.cpp ./temp
cp basic/gl40/gl40-minsampleshading.cpp ./temp
cp basic/gl40/gl40-pausefeedback.cpp ./temp
cp basic/gl40/gl40-pausefeedback.cpp ./temp
cp basic/gl40/gl40-drawfeedbackstream.cpp ./temp
cp basic/gl40/gl40-drawtransformfeedback.cpp ./temp
cp basic/gl40/gl40-drawtransformfeedback.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/rop-sample.cpp ./temp
cp basic/gl33/gl33-FragData.cpp ./temp
cp basic/gl33/gl33-Samplers.cpp ./temp
cp basic/gl33/gl33-Samplers.cpp ./temp
cp basic/gl33/gl33-Samplers.cpp ./temp
cp basic/gl33/gl33-Samplers.cpp ./temp
cp basic/gl33/gl33-Samplers.cpp ./temp
cp basic/gl33/gl33-Samplers.cpp ./temp
cp basic/gl33/gl33-VertexAttribDivisor.cpp ./temp
cp basic/gl33/gl33-VertexAttribDivisor.cpp ./temp
cp basic/gl33/gl33-VertexAttribDivisor.cpp ./temp
cp basic/gl33/gl33-VertexAttribDivisor.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl33/gl33-VertexAttribP.cpp ./temp
cp basic/gl32/gl32-Sync.cpp ./temp
cp basic/gl32/gl32-Sync.cpp ./temp
cp basic/gl32/gl32-Sync.cpp ./temp
cp basic/gl32/gl32-Sync.cpp ./temp
cp basic/gl32/gl32-Sync.cpp ./temp
cp basic/gl32/gl32-ProvokingVertex.cpp ./temp
cp basic/gl32/gl32-ProvokingVertex.cpp ./temp
cp basic/gl32/gl32-MultiDrawElementsBaseVertex.cpp ./temp
cp basic/gl32/gl32-GetBufferParameteri64v.cpp ./temp
cp basic/gl32/gl32-GetBufferParameteri64v.cpp ./temp
cp basic/gl32/gl32-GetBufferParameteri64v.cpp ./temp
cp basic/gl32/gl32-GetBufferParameteri64v.cpp ./temp
cp basic/gl32/gl32-DrawrRangeElementsBaseVertex.cpp ./temp
cp basic/gl32/gl32-DrawElementsInstancedBaseVertex.cpp ./temp
cp basic/gl32/gl32-DrawElementsInstancedBaseVertex.cpp ./temp
cp basic/gl32/gl32-DrawElementsBaseVertex.cpp ./temp
cp basic/gl31/gl31-CopyBufferSubData.cpp ./temp
cp basic/gl31/gl31-GetActiveUniformName.cpp ./temp
cp basic/gl31/gl31-GetActiveUniformName.cpp ./temp
cp basic/gl31/gl31-GetActiveUniformName.cpp ./temp
cp basic/gl31/gl31-GetActiveUniformName.cpp ./temp
cp basic/gl31/gl31-GetActiveUniformName.cpp ./temp
cp basic/gl31/gl31-GetActiveUniformName.cpp ./temp
cp basic/gl31/gl31-GetActiveUniformName.cpp ./temp
cp basic/gl31/gl31-GetUniformIndices.cpp ./temp
cp basic/gl31/gl31-PrimitiveRestartIndex.cpp ./temp
cp basic/gl31/gl31-TexBuffer.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BeginTransformFeedback.cpp ./temp
cp basic/gl30/gl30-BindBufferRange.cpp ./temp
cp basic/gl30/gl30-GetVertexAttribIiv.cpp ./temp
cp basic/gl30/gl30-GetVertexAttribIuiv.cpp ./temp
cp basic/gl30/gl30-VertexAttribIPointer.cpp ./temp
cp basic/gl30/gl30-colormaski.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI2\&2i.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI1\&2iv.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI1\&2iv.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI2\&2ui.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI3\&1i.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI3\&1i.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI3iv.cpp ./temp
cp basic/gl30/gl30-glVertexAttribI4iv.cpp ./temp
cp basic/gl21/gl21-uniformfv.cpp ./temp
cp basic/gl20/gl20-blendequsep.cpp ./temp
cp basic/gl20/gl20-drawbuffers.cpp ./temp
cp basic/gl20/gl20-stencilsep.cpp ./temp
cp basic/gl20/gl20-stencilsep.cpp ./temp
cp basic/gl20/gl20-stencilsep.cpp ./temp
cp basic/gl20/gl20-uniformfv.cpp
cp basic/gl20/gl20-uniformfv.cpp
cp basic/gl20/gl20-uniformfv.cpp ./temp
cp basic/gl20/gl20-uniformfv.cpp ./temp
cp basic/gl20/gl20-uniformi.cpp ./temp
cp basic/gl20/gl20-uniformi.cpp ./temp
cp basic/gl20/gl20-uniformi.cpp ./temp
cp basic/gl20/gl20-uniformi.cpp ./temp
cp basic/gl20/gl20-uniformiv.cpp ./temp
cp basic/gl20/gl20-uniformiv.cpp ./temp
cp basic/gl20/gl20-uniformiv.cpp ./temp
cp basic/gl20/gl20-uniformiv.cpp ./temp
cp basic/gl20/gl20-uniformmatrix.cpp ./temp
cp basic/gl20/gl20-uniformmatrix.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl20/gl20-vertexattrib.cpp ./temp
cp basic/gl14/gl14-blendequ.cpp ./temp
cp basic/gl14/gl14-multidrawarrays.cpp ./temp
cp basic/gl14/gl14-multidrawelements.cpp ./temp
cp basic/gl14/gl14-points.cpp ./temp
cp basic/gl14/gl14-points.cpp ./temp
cp basic/gl14/gl14-points.cpp ./temp
cp basic/gl14/gl14-points.cpp ./temp
cp basic/gl13/gl13-arrayelement.cpp ./temp
cp basic/gl13/gl13-clientattrib.cpp ./temp
cp basic/gl13/gl13-copytex.cpp ./temp
cp basic/gl13/gl13-copytex.cpp ./temp
cp basic/gl13/gl13-copytex.cpp ./temp
cp basic/gl13/gl13-copytex.cpp ./temp
cp basic/gl13/gl13-depth.cpp ./temp
cp basic/gl13/gl13-depth.cpp ./temp
cp basic/gl13/gl13-depth.cpp ./temp
cp basic/gl13/gl13-drawbuffer.cpp ./temp
cp basic/gl13/gl13-frustumortho.cpp ./temp
cp basic/gl13/gl13-getstring.cpp ./temp
cp basic/gl13/gl13-line.cpp ./temp
cp basic/gl13/gl13-mipmap.cpp ./temp
cp basic/gl13/gl13-polygonoffset.cpp ./temp
cp basic/gl13/gl13-prim.cpp ./temp
cp basic/gl13/gl13-texgen.cpp ./temp
cp basic/gl13/gl13-texprox.cpp ./temp
cp basic/gl13/gl13-texture3d.cpp ./temp
cp basic/gl13/gl13-wave.cpp ./temp
cp basic/gl13/gl13-compresstex.cpp ./temp
cp shader/gl43/gl43_Layer.cpp ./temp
cp basic/es30/es30-vertexattribipointer.cpp ./temp
cp basic/es30/es30-buffersubdata.cpp ./temp
cp basic/es30/es30-texstorage3d-2darray.cpp ./temp
cp basic/es30/es30-texcopysub3d-2darray.cpp ./temp
cp basic/es30/es30-uniformuiv.cpp ./temp
cp basic/es30/es30-uniformuiv.cpp ./temp
cp basic/es30/es30-uniformuiv.cpp ./temp
cp basic/es30/es30-uniformuiv.cpp ./temp
cp basic/es30/es30-clearbuffer.cpp ./temp
cp basic/es30/es30-clearbuffer.cpp ./temp
cp basic/es30/es30-clearbuffer.cpp ./temp
cp basic/es30/es30-subdatasync.cpp ./temp
cp basic/es30/es30-sampler-mipmap.cpp ./temp
cp basic/es30/es30-uniformmatrix3x4fv.cpp ./temp
cp basic/es30/es30-texcompress3d.cpp ./temp
cp basic/es30/es30-uniformmatrix3x2fv.cpp ./temp
cp basic/es30/es30-clearbuffercolorformat.cpp ./temp
cp basic/es30/es30-uniformmatrix4x2fv.cpp ./temp
cp basic/es30/es30-uniformmatrix2x4fv.cpp ./temp
cp basic/es30/es30-uniformui.cpp ./temp
cp basic/es30/es30-uniformui.cpp ./temp
cp basic/es30/es30-uniformui.cpp ./temp
cp basic/es30/es30-uniformui.cpp ./temp
cp basic/es30/es30-transfeedbackubo.cpp ./temp
cp basic/es30/es30-framebuffermultisample.cpp ./temp
cp basic/es30/es30-vertexarrays.cpp ./temp
cp basic/es30/es30-uniformblock.cpp ./temp
cp basic/es30/es30-uniformmatrix4x3fv.cpp ./temp
cp basic/es30/es30-vertexattribi.cpp ./temp
cp basic/es30/es30-vertexattribi.cpp ./temp
cp basic/es30/es30-vertexattribi.cpp ./temp
cp basic/es20/es20-framebufferobject.cpp ./temp
cp basic/es20/es20-shaderbinary.cpp ./temp
cp basic/es20/es20-shaderbinary.cpp ./temp
cp basic/es20/es20-shaderbinary.cpp ./temp
cp basic/es20/es20-shaderbinary.cpp ./temp
cp basic/es20/es20-blendfuncsep.cpp ./temp
cp basic/es20/es20-program.cpp ./temp
cp basic/es20/es20-vertexattrib.cpp ./temp
cp basic/es31/es31-gettexparameteriv.cpp ./temp
cp basic/es31/es31-program-pipeline.cpp ./temp
cp basic/es31/es31-computeshader.cpp? ./temp
cp basic/es31/es31-bindvertexbuffer.cpp ./temp
cp basic/es32/es32-draweleinsbasevert.cpp ./temp
cp basic/es32/es32-getuniform.cpp ./temp
cp basic/es32/es32-colormaski.cpp ./temp
cp basic/es32/es32-blendbarrier.cpp ./temp
cp basic/es32/es32-blendbarrier.cpp ./temp

